title: "Franklin"
sass:
    sass_dir: _sass
include:
  - _projects
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - gulpfile.js
encoding: "utf-8"
